#Springboot Service
FROM amazoncorretto:22 AS build
WORKDIR /app
COPY backend/pom.xml ./
RUN yum install -y maven
COPY backend/src ./src
RUN mvn clean package -DskipTests


#Run
FROM amazoncorretto:22-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]

