# React Service
FROM node:18-slim as react-build
WORKDIR /app/
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

#Run
FROM node:18-slim
WORKDIR /app
COPY --from=react-build /app/build ./build
RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "build"]
